/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.68
 * Generated at: 2016-05-23 04:32:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.join;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class idcheck_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String root = request.getContextPath();

String id = (String) request.getAttribute("searchid");

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(root );
      out.write("/css/style.css\" type=\"text/css\">\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function idcheck(){\r\n");
      out.write("\tif(document.getElementById(\"id\").value == \"\") {\r\n");
      out.write("\t\talert(\"검색 아이디 입력!\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t} else {\r\n");
      out.write("\t\tdocument.idform.action = \"");
      out.print(root);
      out.write("/member\";\r\n");
      out.write("\t\tdocument.idform.submit();\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function iduse(id){\r\n");
      out.write("\topener.document.getElementById(\"id\").value = id;\r\n");
      out.write("\tself.close();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<center>\r\n");
      out.write("<form name=\"idform\" method=\"get\" action=\"\" onsubmit=\"return false;\">\r\n");
      out.write("<input type=\"hidden\" name=\"act\" value=\"idsearch\">\r\n");
      out.write("<h3>아이디 중복 검사</h3>\r\n");
      out.write("<table width=\"350\">\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td class=\"td3\">검색할 아이디를 입력하세요</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td class=\"td4\" style=\"text-align: center\">\r\n");
      out.write("\t<input type=\"text\" name=\"id\" id=\"id\" onkeypress=\"javascript:if(event.keyCode == 13){ idcheck(); }\">\r\n");
      out.write("\t<input type=\"button\" value=\"검색\" onclick=\"javascript:idcheck();\">\r\n");
      out.write("\t</td>\r\n");
      out.write("</tr>\r\n");

if(id == null) {

      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td class=\"td4\">\r\n");
      out.write("\t검색할 아이디를 정확히 입력한 후 검색 버튼을 클릭하세요..\r\n");
      out.write("\t</td>\r\n");
      out.write("</tr>\r\n");

} else {
	int cnt = (Integer) request.getAttribute("count");
	if(cnt == 0) {

      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td class=\"td4\">\r\n");
      out.write("\t<b>");
      out.print(id );
      out.write("</b>는 사용가능합니다.\r\n");
      out.write("\t<input type=\"button\" value=\"사용\" onclick=\"javascript:iduse('");
      out.print(id );
      out.write("');\">\r\n");
      out.write("\t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\t");

	} else {
	
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td class=\"td4\">\r\n");
      out.write("\t<b>");
      out.print(id );
      out.write("</b>는 사용할수 없습니다.<br>\r\n");
      out.write("\t다른 아이디로 검색하세요.\r\n");
      out.write("\t</td>\r\n");
      out.write("</tr>\r\n");

	}
}

      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
