/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.68
 * Generated at: 2016-05-23 04:25:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.join;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class member_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	String root = request.getContextPath();

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(root );
      out.write("/css/style.css\" type=\"text/css\">\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function join(){\r\n");
      out.write("\tif(document.getElementById(\"id\").value == \"\") {\r\n");
      out.write("\t\talert(\"아이디 입력!\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t} else if(document.getElementById(\"name\").value == \"\") {\r\n");
      out.write("\t\talert(\"이름 입력!\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t} else if(document.getElementById(\"pass\").value  == \"\") {\r\n");
      out.write("\t\talert(\"비밀번호 입력!\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t} else if(document.getElementById(\"pass\").value != document.getElementById(\"passcheck\").value) {\r\n");
      out.write("\t\talert(\"비밀번호 확인!\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t} else {\r\n");
      out.write("\t\tdocument.joinform.action = \"");
      out.print(root);
      out.write("/member\";\r\n");
      out.write("\t\tdocument.joinform.submit();\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function openzip(){\r\n");
      out.write("\twindow.open(\"");
      out.print(root);
      out.write("/member?act=mvzip\",\"\",\"top=200, left=300, width=400, height=300, menubar=no, status=no, toolbar=no, location=no, scrollbars=yes\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function openidcheck(){\r\n");
      out.write("\twindow.open(\"");
      out.print(root);
      out.write("/member?act=mvidcheck\",\"\",\"top=200, left=300, width=400, height=180, menubar=no, status=no, toolbar=no, location=no, scrollbars=no\");\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write(" </head>\r\n");
      out.write("\r\n");
      out.write(" <body>\r\n");
      out.write("  <center>\r\n");
      out.write("\t<h3>회원가입</h3>\r\n");
      out.write("\t<form name =\"joinform\" method=\"post\" action=\"\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"act\" value=\"register\">\r\n");
      out.write("\t <table width=\"780\" height=\"700\" cellspacing=\"4\" cellpadding=\"5\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t <td class=\"td1\">이름<font color=\"red\">*</font></td>\r\n");
      out.write("\t\t\t <td class=\"td3\"><input type=\"text\" name=\"name\" id=\"name\" value=\"\" size=\"12\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("<!--\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t <td class=\"td2\">주민등록번호<font color=\"red\">*</font></td>\r\n");
      out.write("\t\t\t <td class=\"td4\"><input type=\"text\" name=\"reginum1\" value=\"\" size=\"12\" maxlength=\"6\"> -\r\n");
      out.write("\t\t\t <input type=\"text\" name=\"reginum2\" value=\"\" size=\"12\" maxlength=\"7\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t <td class=\"td1\">닉네임(별명)<font color=\"red\">*</font></td>\r\n");
      out.write("\t\t\t <td class=\"td3\"><input type=\"text\" name=\"nickname\" value=\"\" size=\"12\">&nbsp;&nbsp; 실명을 사용하지 않는 서비스에서 사용되는 <font color=\"#3cb371\">별명</font>입니다.<br>입력하지 않으실 경우 회원님의 이름이 등록됩니다.</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t <td class=\"td2\">아이디(ID)<font color=\"red\">*</font></td>\r\n");
      out.write("\t\t\t <td class=\"td4\"><input type=\"text\" name=\"id\" id=\"id\" value=\"\" size=\"12\">\r\n");
      out.write("\t\t\t  <input type=\"button\" value=\"아이디중복검사\" onclick=\"javascript:openidcheck()\">\r\n");
      out.write("\t\t\t &nbsp;&nbsp;<font color=\"#3cb371\">4~12</font>자이내 영문이나 숫자(영문은 대소문자를 구별하므로 주의해주세요</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t <td class=\"td1\">비밀번호입력<font color=\"red\">*</font></td> \r\n");
      out.write("\t         <td class=\"td3\"><input type=\"password\" name=\"pass\" id=\"pass\" size=\"12\" maxlength=\"12\">&nbsp;&nbsp;<font color=\"#3cb371\">6~12</font>자리의 영문(대소문자 구별)이나 숫자</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t <td class=\"td2\">비밀번호확인<font color=\"red\">*</font></td> \r\n");
      out.write("\t         <td class=\"td4\"><input type=\"password\" name=\"passcheck\" id=\"passcheck\" size=\"12\" maxlength=\"12\">&nbsp;&nbsp;비밀번호를 한번더 입력하세요</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("<!--\r\n");
      out.write("            <tr>\r\n");
      out.write("\t\t\t <td width=\"120\" class=\"td1\">비밀번호 재발급<font color=\"red\">*</font><br>질문 선택</td>\r\n");
      out.write("\t\t\t <td class=\"td3\">\r\n");
      out.write("\t\t\t  <select name=\"question\">\r\n");
      out.write("\t\t\t   <option value=\"\">가장 좋아하는 색상은?(예: 빨강)</option>\r\n");
      out.write("\t\t\t   <option value=\"\">어릴 적 단짝 친구의 이름은?</option>\r\n");
      out.write("\t\t\t   <option value=\"\">가장 좋아하는 음식은?</option>\r\n");
      out.write("\t\t\t   <option value=\"\">가장 여행하고 싶은 나라는?</option>\r\n");
      out.write("\t\t\t   <option value=\"\">기억에 남는 추억의 장소는?</option>\r\n");
      out.write("\t\t\t   <option value=\"\">가장 좋아하는 연예인은?</option>\r\n");
      out.write("\t\t\t  <option value=\"\">친구들에게 공개하지 않은 어릴 적 별명이 있다면?</option>\r\n");
      out.write("\t\t\t  </select><br>\r\n");
      out.write("\t\t\t  혹시 비밀번호를 잊어버리신 경우 여기에서 선택한 질문을 하게됩니다.\r\n");
      out.write("\t\t\t </td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t <td width=\"120\" class=\"td2\">비밀번호 재발급<font color=\"red\">*</font><br>답변 입력</td> \r\n");
      out.write("\t         <td class=\"td4\"><input type=\"text\" name=\"answer\" size=\"35\"><br>\r\n");
      out.write("\t\t\t 위에서 선택하신 질문에 대한 답변을 입력하세요.<br>\r\n");
      out.write("\t\t\t 비밀번호를 잊어버리신 경우 이 답변을 이용하여 비밀번호를 재발급 받으실 수 있습니다.</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("-->\r\n");
      out.write("\t\t    <tr>\r\n");
      out.write("\t\t\t <td class=\"td1\">연락처<font color=\"red\">*</font></td>\r\n");
      out.write("\t\t\t <td class=\"td3\">\r\n");
      out.write("\t\t\t  휴 대 폰&nbsp;&nbsp;<select name=\"tel1\">\r\n");
      out.write("\t\t\t   <option value=\"\">----</option>\r\n");
      out.write("\t\t       <option value=\"010\">010</option>\r\n");
      out.write("\t\t\t   <option value=\"010\">011</option>\r\n");
      out.write("\t\t\t   <option value=\"010\">016</option>\r\n");
      out.write("\t\t\t   <option value=\"010\">017</option>\r\n");
      out.write("\t\t\t   <option value=\"010\">018</option>\r\n");
      out.write("\t\t\t  </select> -\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"tel2\" value=\"\" size=\"4\" maxlength=\"4\" > -\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"tel3\" value=\"\" size=\"4\" maxlength=\"4\" ><br>\r\n");
      out.write("<!--\r\n");
      out.write("\t\t\t  유선전화&nbsp;<select name=\"tel1\">\r\n");
      out.write("\t\t\t   <option value=\"\">----</option>\r\n");
      out.write("\t\t       <option value=\"010\">02</option>\r\n");
      out.write("\t\t\t   <option value=\"010\">031</option>\r\n");
      out.write("\t\t\t   <option value=\"010\">032</option>\r\n");
      out.write("\t\t\t   <option value=\"010\">033</option>\r\n");
      out.write("\t\t\t   <option value=\"010\">041</option>\r\n");
      out.write("\t\t\t  </select> -\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"tel2\" value=\"\" size=\"4\" maxlength=\"4\" > -\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"tel3\" value=\"\" size=\"4\" maxlength=\"4\" >\r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"location\" value=\"집\" checked>집\r\n");
      out.write("        \t        <input type=\"radio\" name=\"location\" value=\"회사\">회사\r\n");
      out.write("\t\t\t\t\t<br>휴대폰이나 유선전화 중에서 <font color=\"#3cb371\">하나는 반드시 입력하셔야 합니다.</font>\r\n");
      out.write("-->\r\n");
      out.write("\t\t\t </td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t <td class=\"td2\">우편번호<font color=\"red\">*</font></td>\r\n");
      out.write("\t\t\t <td class=\"td4\"><input type=\"text\" name=\"zip1\" value=\"\" size=\"5\" maxlength=\"3\"  readonly=\"readonly\"> -\r\n");
      out.write("\t\t\t <input type=\"text\" name=\"zip2\" value=\"\" size=\"5\" maxlength=\"3\"  readonly=\"readonly\">\r\n");
      out.write("\t\t\t <input type=\"button\" value=\"우편번호검색\"  onclick=\"javascript:openzip();\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t <td class=\"td1\">주소<font color=\"red\">*</font></td>\r\n");
      out.write("\t\t\t <td class=\"td3\"><input type=\"text\" name=\"addr1\" value=\"\" size=\"100\"  readonly=\"readonly\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t <td class=\"td2\">상세주소<font color=\"red\">*</font></td>\r\n");
      out.write("\t\t\t <td class=\"td4\"><input type=\"text\" name=\"addr2\" size=\"100\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("\t\t\t <td class=\"td1\">주로 쓰는 이메일<font color=\"red\">*</font></td>\r\n");
      out.write("\t\t\t <td class=\"td3\"><input type=\"text\" name=\"email1\" value=\"\" size=\"12\"> @\r\n");
      out.write("\t\t\t\t\t<!--<input type=\"text\" name=\"direct\" value=\"\" size=12>-->\r\n");
      out.write("\t                <select name=\"email2\">\r\n");
      out.write("\t\t\t\t\t<!--<option value=\"naver.com\">직접입력</option>-->\r\n");
      out.write("\t\t            <option value=\"naver.com\">naver.com</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"hanmail.net\">hanmail.net</option>\r\n");
      out.write("\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("<!--\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t <td class=\"td2\">성별<font color=\"red\">*</font></td> \r\n");
      out.write("\t         <td class=\"td4\"><input type=\"radio\" name=\"gender\" value=\"남\" checked>남자\r\n");
      out.write("        \t        <input type=\"radio\" name=\"gender\" value=\"여\">여자</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t <td class=\"td1\">결혼여부<font color=\"red\">*</font></td> \r\n");
      out.write("\t         <td class=\"td3\"><input type=\"radio\" name=\"married\" value=\"미혼\" checked>미혼 \r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"married\" value=\"기혼\">기혼</td>\r\n");
      out.write("        \t   \r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t <td class=\"td2\">취미 & 관심사항</td>\r\n");
      out.write("\t\t\t <td class=\"td4\"><input type=\"checkbox\" name=\"컴퓨터\">컴퓨터&nbsp;&nbsp;&nbsp;&nbsp;<input type=\"checkbox\" name=\"게임\">게임&nbsp;&nbsp;&nbsp;&nbsp;<input type=\"checkbox\" name=\"음악\">음악&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t    <input type=\"checkbox\" name=\"연예\">연예&nbsp;&nbsp;&nbsp;&nbsp;<input type=\"checkbox\" name=\"뉴스\">뉴스&nbsp;&nbsp;&nbsp;&nbsp;<input type=\"checkbox\" name=\"IT\">IT&nbsp;&nbsp;&nbsp;&nbsp;<input type=\"checkbox\" name=\"맛집\">맛집&nbsp;&nbsp;&nbsp;&nbsp;<input type=\"checkbox\" name=\"IT\">맛집\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("-->\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("             <td colspan=\"2\" align=\"center\">\r\n");
      out.write("             <input type=\"button\" value=\"회원가입\" onclick=\"javascript:join();\">\r\n");
      out.write("&nbsp;&nbsp;\r\n");
      out.write("\t          <input type=\"reset\" value=\"취소\">\r\n");
      out.write("\t         </td>\r\n");
      out.write("\t   \t\t</tr>\r\n");
      out.write("   </table>\r\n");
      out.write("   </form>\r\n");
      out.write("  </center>\r\n");
      out.write(" </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
